Repository EddieHubCommunity/awesome-github-profiles, pull requests merged in 2021-12, with the labels that each got.

#652 feat: Use the Cayman theme, update for the new API changes, and more
  .github/workflows/main.yml
  README.md
  _config.yml
  _layouts/default.html
  assets/css/style.scss
  profiles.md
Labels: enhancement

#879 fix: Prettier issues
  _config.yml
  _layouts/default.html
Labels: bug

#878 fix: move text from `README.md` to `profiles.md`
  README.md
  profiles.md
Labels: documentation

#885 docs: add link to the profiles folder in readme
  README.md
Labels: bug

#889 docs: update PR template
  .github/pull_request_template.md
Labels: documentation

#888 docs: update readme JSON's example content
  README.md
Labels: documentation

#895 fix: Update my profile's screenshot
  profiles.md
  profiles/Panquesito7.json
Labels: enhancement

#896 docs: improve the pull request template
  .github/pull_request_template.md
Labels: documentation

#900 fix: Prettier issues
  .github/pull_request_template.md
  README.md
  package.json
  profiles/Pradumnasaraf.json
  profiles/codlipa.json
  profiles/kumarsonsoff3.json
  profiles/ravithemore.json
  profiles/samuelbartels20.json
Labels: bug

#908 docs: Updated PR title in Readme an PR template.
  .github/pull_request_template.md
  README.md
Labels: documentation

#910 fix: Prettier issues
  profiles/artimanputra.json
Labels: enhancement

#935 Cahllagerfeld/request-url
  assets/config/config.js
  pages/api/profiles.js
  pages/index.js
Labels: enhancement
